/* Player Introductions */
const playersScroller = scrollama(); /* Initiates scrollama for the section/function */

playersScroller
.setup({ 
    step: '.player_individual_step', /* defines the steps */
    offset: 0.5 /* defines when the step is triggered, based on how far down the screen the user scrolls */
})
.onStepEnter(({ element }) => { playerHandleStep(element); }) /* tells function to run when a step is entered */

function playerHandleStep(element) {  /* when a step is entered, pulls the corresponding figure*/
    const playerIntroStep = element.dataset.figure;
    document.querySelectorAll('[class^="player_figure"]').forEach(el => el.classList.remove('active')); /* selector for anything with the class 'player_figure' (=^) and removes their active class so that only one can be defined as active at a time, making it the visible step*/
    document.querySelector('.player_figure' + playerIntroStep).classList.add('active'); /* adds the active class to one step at a time, making it visible */
} 

/* The above commented explanations also apply to the methodology cards and key findings sections */

/* Methodology Cards*/
const appearingCardsScroller = scrollama();

appearingCardsScroller
.setup({
    step: '.scroll_trigger',
    offset: 0.5,
})

.onStepEnter(({ element }) => {
    const appearingCardsStep = element.dataset.step;
    document.querySelectorAll('.single_appearing_card').forEach(el => {el.classList.remove('active'); 
    });
    document.querySelector(`[data-appearing_text="${appearingCardsStep}"]`).classList.add('active');
})

.onStepExit(({ element }) => {});

/* Key Findings */
const keyFindingsScroller = scrollama();

keyFindingsScroller
.setup({ 
    step: '.step',
    offset: 0.5
})
.onStepEnter(({ element }) => { handleStep(element); })

function handleStep(element) { 
    const keyFindingsStep = element.dataset.figure;
    document.querySelectorAll('[class^="figure"]').forEach(el => el.classList.remove('active'));
    document.querySelector('.figure' + keyFindingsStep).classList.add('active');
} 

/* Pawn Animation */

/*Calculation of Pawn's starting position. Runs once on page load */

/* The following 30 lines were generated by Claude AI. This first block replaced my manual calculations of the pawn's position to automate the process and make it more robust. The second keeps the pawn's coordinates relevant to the correct textbox if the page is resized*/
window.addEventListener('load', () => {
    const boxOne = document.querySelector('.pawn_textbox[data-text="1"]');
    const container = document.querySelector('.pawn_sticky_background');
    const boxLocation = boxOne.getBoundingClientRect();
    const containerLocation = container.getBoundingClientRect();
    const pawn = document.querySelector('.pawn');

    pawn.style.transition = 'none';

    pawn.style.top = (boxLocation.top - containerLocation.top + 40) + 'px';
    pawn.style.left = (boxLocation.left - containerLocation.left - 42) + 'px';

    pawn.offsetHeight;

    pawn.style.transition = '';
});

// keeps the pawn position synced to its active box on window resize
window.addEventListener('resize', () => {
    const activePawnBox = document.querySelector('.pawn_textbox.active') || document.querySelector('.pawn_textbox[data-text="1"]');
    const containerLocation = document.querySelector('.pawn_sticky_background').getBoundingClientRect();
    const boxLocation = activePawnBox.getBoundingClientRect();
    const pawn = document.querySelector('.pawn');
    pawn.style.transition = 'none';
    pawn.style.top = (boxLocation.top - containerLocation.top + 40) + 'px';
    pawn.style.left = (boxLocation.left - containerLocation.left - 42) + 'px';
    pawn.offsetHeight;
    pawn.style.transition = '';
});

/* End of AI-generated section */

const pawn_effect = scrollama();

pawn_effect
.setup ({
    step: '.pawn_info',
    offset: 0.8,
    progress: true /* Fires 'onStepProgress' repeatedly to track how far the user has scrolled through a step and drive the opacity level of the fading-in textboxes  */
})
.onStepEnter (({ element }) => {
    const pawnStepBetweenBoxes = element.dataset.pawn; /*when a step is entered, pulls the corresponding figure from the element's data-figure attribute*/
    const pawnBox = document.querySelector(
            `.pawn_textbox[data-text="${pawnStepBetweenBoxes}"]`
        );
    const pawnBoxLocation = pawnBox.getBoundingClientRect(); /* Finds the location of each textbox */
    const pawnContainerLocation = document.querySelector('.pawn_sticky_background').getBoundingClientRect(); /*Finds the coordinates of the sticky background */
    pawnBox.classList.add('active') /* Adds active class to the appropriate textbox */

    document.querySelector('.pawn').style.top = (pawnBoxLocation.top - pawnContainerLocation.top + 40) + 'px'; /*Moves the pawn downwards (changes its vertical coordinates) to the next box, according to the coordinates of the background and the textbox. 
                                                                                                                Subtracts the background coordinates from the textbox location in order to take into account how other large
                                                                                                                objects in the document may effect the position of the current elements to get a more accurate intended position for the pawn to move to */
    document.querySelector('.pawn').style.left = (pawnBoxLocation.left - pawnContainerLocation.left - 42) + 'px'; /* Does the same as above, but handles the pawn's horizontal coordinates. The '40' and '42' are manually chosen numbers based on what looked best visually */
})

.onStepProgress(pawn_animation_progress => {
    const pawnStepBetweenBoxes = pawn_animation_progress.element.dataset.pawn; /* Selects the pawn */
    const pawnAppear = pawn_animation_progress.progress; 
    const pawnCardText = document.querySelector(`[data-text="${pawnStepBetweenBoxes}"]`); /* Selects the correct text to make it appear upon scroll */
    pawnCardText.style.opacity = pawnAppear; /*Fades in textboxes when active */
})

.onStepExit(({ element }) => {});


/* Bishop Animation */

/*Calculation of bishop's starting position. Runs once on page load */

/* As with the code that calculates the bishop's starting position, the following 30 lines were generated by Claude AI */

window.addEventListener('load', () => {
    const boxOne = document.querySelector('.bishop_textbox[data-text="1"]');
    const container = document.querySelector('.bishop_sticky_background');
    const boxLocation = boxOne.getBoundingClientRect();
    const containerLocation = container.getBoundingClientRect();

    const bishop = document.querySelector('.bishop');

    bishop.style.transition = 'none'; // disables the animation before setting position

    bishop.style.top = (boxLocation.top - containerLocation.top + 28) + 'px';
    bishop.style.left = (boxLocation.left - containerLocation.left - 42) + 'px';

    bishop.offsetHeight; // forces the browser to apply the position immediately

    bishop.style.transition = ''; // restores the CSS transition for future step changes
});


window.addEventListener('resize', () => {
    const activeBox = document.querySelector('.bishop_textbox.active') || document.querySelector('.bishop_textbox[data-text="1"]');
    const containerLocation = document.querySelector('.bishop_sticky_background').getBoundingClientRect();
    const boxLocation = activeBox.getBoundingClientRect();
    const bishop = document.querySelector('.bishop');
    bishop.style.transition = 'none';
    bishop.style.top = (boxLocation.top - containerLocation.top + 28) + 'px';
    bishop.style.left = (boxLocation.left - containerLocation.left - 42) + 'px';
    bishop.offsetHeight;
    bishop.style.transition = '';
});

/* End of AI-generated section */

const bishopEffect = scrollama();

bishopEffect /* Works in the same way as the pawn effect. The bishop moves diagonally due to the CSS positioning of the textboxes */
.setup ({
    step: '.bishop_info',
    offset: 1,
    progress: true
})

.onStepEnter (({ element }) => {
    const stepBetweenBoxes = element.dataset.bishop;
    const box = document.querySelector(`.bishop_textbox[data-text="${stepBetweenBoxes}"]`);
    const boxLocation = box.getBoundingClientRect();
    const containerLocation = document.querySelector('.bishop_sticky_background').getBoundingClientRect();
    box.classList.add('active')

    document.querySelector('.bishop').style.top = (boxLocation.top - containerLocation.top + 28) + 'px';
    document.querySelector('.bishop').style.left = (boxLocation.left - containerLocation.left - 42) + 'px';
})
.onStepProgress(bishop_animation_progress => {
    const stepBetweenBoxes = bishop_animation_progress.element.dataset.bishop;
    const appear = bishop_animation_progress.progress;
    const cardText = document.querySelector(`.bishop_textbox[data-text="${stepBetweenBoxes}"]`);
    cardText.style.opacity = appear;
})

.onStepExit(({ element }) => {});
